# TP2


## Loading and shaping

In [10]:
import cv2
import numpy as np
from numpy.typing import NDArray
import matplotlib.pyplot as plt

def load_img(path: str) -> NDArray:
    img = cv2.imread(path, cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

image = load_img("data/kodim01.png")
#image dimensions saved for later
w, h, _ = image.shape
# Reshape image as vector of rgb for easier treatment
vec = np.reshape(image, (-1, 3))

## Operations

In [11]:

avg = np.average(vec, axis=0)
centered = vec - avg
cov = np.cov(centered.T)
print(f"Covariance matrix: \n{cov}")

h = np.linalg.eig(cov)
altered_eiv = np.zeros((3,3,3))
altered_imgs = np.zeros((3, *vec.shape))
for i in range(3):
    eiv = h.eigenvectors.copy()
    eiv[i,:] = 0
    altered_eiv[i,:,:] = eiv
    # Applies eiv to each pixel of vec
    altered_imgs[i, :, :] = np.einsum("ij,kj->ik", vec, eiv)


Covariance matrix: 
[[1192.50573385 1332.56841064 1163.60433579]
 [1332.56841064 2000.75580572 1778.77761116]
 [1163.60433579 1778.77761116 1609.11460684]]


In [13]:

# Code to get the original image back in shape
# back = np.reshape(vec, (w, h, 3))
# plt.imshow(back)
# plt.show()